---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-io-redis-v1-replication
  failurePolicy: Fail
  name: mreplication-v1.kb.io
  rules:
  - apiGroups:
    - k8s.io.redis
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replications
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-io-redis-v1-cluster
  failurePolicy: Fail
  name: vcluster-v1.kb.io
  rules:
  - apiGroups:
    - k8s.io.redis
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-io-redis-v1-standalone
  failurePolicy: Fail
  name: vstandalone-v1.kb.io
  rules:
  - apiGroups:
    - k8s.io.redis
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - standalones
  sideEffects: None
