# permissions for end users to edit standalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: standalone-editor-role
rules:
- apiGroups:
  - k8s.io.redis
  resources:
  - standalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.io.redis
  resources:
  - standalones/status
  verbs:
  - get
