apiVersion: k8s.io.redis/v1
kind: Replication
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: replication-sample
spec:
  # TODO(user): Add fields here
