apiVersion: k8s.io.redis/v1
kind: Sentinel
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: sentinel-sample
spec:
  # TODO(user): Add fields here
